disabled_rules:
  - trailing_whitespace

excluded:
  - .build
  - DerivedData
  - build
  - iOS/build
  - macOS/build
  - Modules/**/.build
  - Packages/**/.build

opt_in_rules:
  - empty_count
  - explicit_init
  - first_where
  - fatal_error_message

line_length:
  warning: 140
  error: 180

file_length:
  warning: 800
  error: 1200

type_body_length:
  warning: 300
  error: 500

function_body_length:
  warning: 80
  error: 120
